# Daily-Dose-of-Data-Science

[Daily Dose of Data Science](https://avichawla.substack.com) is a publication on Substack that brings together intriguing frameworks, libraries, technologies, and tips that make the life cycle of a Data Science project effortless. 

Author: Avi Chawla

[Medium](https://medium.com/@avi_chawla) | [LinkedIn](https://www.linkedin.com/in/avi-chawla/)

# The Coolest Jupyter Notebook Hack

Post Link: [Substack](https://avichawla.substack.com/p/the-coolest-jupyter-notebook-hack)

LinkedIn Post: [LinkedIn](https://www.linkedin.com/posts/activity-7017794433534312448-3IkS?utm_source=post_nba&utm_medium=member_desktop&utm_campaign=copy)

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

### Method 1

In [3]:
_2

array([1, 2, 3])

### Method 2

In [4]:
Out[2]

array([1, 2, 3])

### Method 3

In [5]:
_oh[2]

array([1, 2, 3])